# Generated by Django 3.0.5 on 2020-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
