# Generated by Django 3.0.5 on 2020-08-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_access_avatar_avatarbase_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='url',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarbase',
            name='url',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.Avatar'),
            preserve_default=False,
        ),
    ]
