# Generated by Django 3.0.5 on 2020-08-23 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200824_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='connect_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='access',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.localtime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='request_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='access',
            name='view_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.localtime),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connect',
            name='retain1_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='retain2_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='retain_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='avatarbase',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mood',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.Avatar'),
        ),
    ]
