# Generated by Django 3.0.5 on 2020-08-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200824_0421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': 'accesses'},
        ),
    ]
