# Generated by Django 3.0.5 on 2020-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_profile_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connect',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
