# Generated by Django 3.0.5 on 2020-08-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200826_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='personality',
            new_name='_personality',
        ),
    ]
