# Generated by Django 3.0.5 on 2020-08-26 22:32

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200826_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='url',
        ),
        migrations.RemoveField(
            model_name='avatarbase',
            name='url',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='temp', upload_to=backend.models.avatar_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatarbase',
            name='image',
            field=models.ImageField(default='temp', upload_to=backend.models.avatar_base_path),
            preserve_default=False,
        ),
    ]
