# Generated by Django 3.0.5 on 2020-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200827_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('trait', models.IntegerField(choices=[(0, 'Earth'), (1, 'Fire'), (2, 'Water'), (3, 'Space'), (4, 'Air')])),
                ('intensity', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
