# Generated by Django 3.0.5 on 2020-12-11 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_adjective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjective',
            name='intensity',
        ),
        migrations.AddField(
            model_name='adjective',
            name='facet',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adjective',
            name='pool',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
    ]
