# Generated by Django 3.0.5 on 2020-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201211_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjective',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adjective',
            name='trait',
            field=models.IntegerField(choices=[(0, 'E'), (1, 'N'), (2, 'A'), (3, 'C'), (4, 'O')]),
        ),
    ]
