# Generated by Django 3.0.5 on 2021-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='chat_id',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
