# Generated by Django 3.0.5 on 2021-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_connect_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='chat_id',
            field=models.CharField(max_length=30),
        ),
    ]
