# Generated by Django 3.0.5 on 2021-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20210310_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
