# Generated by Django 3.0.5 on 2021-03-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_personality_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_questionnaire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
