# Generated by Django 3.0.5 on 2021-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20210314_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalityquestionnaire',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='personalityquestionnaire',
            name='submit_time',
        ),
        migrations.RemoveField(
            model_name='personalityquestionnaire',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='personalityquestionnaire',
            name='user',
        ),
        migrations.AddField(
            model_name='personalityquestionnaire',
            name='initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalityquestionnaire',
            name='url',
            field=models.CharField(default='https://tripetto.app/run/YK2S455EX3/', max_length=40),
            preserve_default=False,
        ),
    ]
