# Generated by Django 3.0.5 on 2021-03-27 09:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_profile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='weather',
            field=models.ImageField(default='', upload_to=backend.models.mood_weather_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='v1',
            field=models.ImageField(upload_to=backend.models.avatar_path_v1),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='v2',
            field=models.ImageField(upload_to=backend.models.avatar_path_v2),
        ),
    ]
