# Generated by Django 3.0.5 on 2021-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20210327_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
