# Generated by Django 3.0.5 on 2021-04-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_mood_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Profile')),
            ],
        ),
    ]
