# Generated by Django 3.0.5 on 2021-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20210802_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='block',
            field=models.SmallIntegerField(null=True),
        ),
    ]
